### PR TITLE
Fix #32. Issue number ignored

### LINKED ISSUE #32: issue_number is ignored
From logs, looks like the issue_number is the correct one, but it actually remove comments from another PR.

image

### PR DESCRIPTION
**Pull request by apomalyn**
The `listComments` function needs an issue number but the `issues` arrays could contain an Issue object or a number. This modification ensures the `issues` arrays only contain numbers.

### CODE REVIEW

**Comment by izhangzhihao** [comment]
Build failed, could you please fix the build error?

**Comment by apomalyn** [comment]
Of course! I will fix it ASAP (probably tomorrow morning)

**Comment by thedmeyer** [comment]
would love to see this merged. Thanks!

**Comment by apomalyn** [comment]
@izhangzhihao this is fixed. Don't hesitate to test it on your side if possible 😄

**Comment by izhangzhihao** [comment]
LGTM

**Comment by apomalyn** [comment]
@thedmeyer I did another PR to fix the actions, you can now use the `issue_number` parameter :tada:

**Pull request merged**
